name: giphy_client
description: A Giphy API Client for Dart compatible Web, Flutter, and server-side dart
version: 0.2.0
homepage: https://www.github.com/brianegan/giphy_client
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.3

dev_dependencies:
  test: ^1.17.3
  mockito: ^5.0.7
  coverage: ^1.0.2
  pedantic: ^1.11.0
